In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('C:/Users/IDEH/Downloads/Telegram Desktop/dataset/h.pylori.csv')

In [3]:
data = data.iloc[1:, :]

In [4]:
data

,case no,age,sex,education,job,epigastric pain,fullness,bloating,reflux,halitosis,...,Gastrointestinal bleeding,gastric cancer,peptic ulcer,Gastrointestinal bleeding fam hist,gasrtic cancer fam hist,stomach ulcer,Revisit,treatment result,test result,treatment
1,1.0,43.0,1.0,1.0,fisherman,1.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,NaN
2,2.0,48.0,0.0,1.0,housewife,1.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,0.0,NaN
3,3.0,54.0,1.0,3.0,civil engineer,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,34
4,4.0,31.0,0.0,1.0,housewife,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,3
5,5.0,36.0,1.0,1.0,jobless,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,141.0,25.0,1.0,3.0,doctor,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,NaN,0.0,NaN
142,142.0,38.0,0.0,0.0,housewife,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,34
143,143.0,63.0,0.0,1.0,housewife,1.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0,3
144,144.0,34.0,0.0,1.0,housewife,1.0,1.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN
145,145.0,63.0,1.0,3.0,retired,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN

In [5]:
data['test result '] = data['test result '].replace({2.0: 1.0})

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 1 to 145
Data columns (total 34 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   case no                                                 145 non-null    float64
 1   age                                                     145 non-null    float64
 2   sex                                                     145 non-null    float64
 3   education                                               145 non-null    float64
 4   job                                                     145 non-null    object
 5   epigastric pain                                         142 non-null    float64
 6   fullness                                                144 non-null    float64
 7    bloating                                               145 non-null    float64
 8   reflux                                                  144 non-null    float64
 9   halitosis                                               145 non-null    float64
 10   nausea                                                 145 non-null    float64
 11  vomit                                                   145 non-null    float64
 12   diarrhea                                               145 non-null    float64
 13   constipation                                           145 non-null    float64
 14  months                                                  145 non-null    float64
 15  Hematochezia                                            145 non-null    float64
 16  loss of appetite                                        145 non-null    float64
 17  weight loss                                             145 non-null    float64
 18  night sweating                                          145 non-null    float64
 19  Treatment of previous infection and use of antibiotics  145 non-null    float64
 20   ppi taking                                             145 non-null    float64
 21   nsaid taking                                           145 non-null    float64
 22  alchohlic                                               145 non-null    float64
 23  smoker                                                  144 non-null    float64
 24  Gastrointestinal bleeding                               145 non-null    float64
 25  gastric cancer                                          145 non-null    float64
 26  peptic ulcer                                            145 non-null    float64
 27  Gastrointestinal bleeding fam hist                      145 non-null    float64
 28  gasrtic cancer fam hist                                 145 non-null    float64
 29  stomach ulcer                                           145 non-null    float64
 30  Revisit                                                 144 non-null    float64
 31  treatment result                                        72 non-null     float64
 32  test result                                             144 non-null    float64
 33  treatment                                               69 non-null     object
dtypes: float64(32), object(2)
memory usage: 38.6+ KB

In [19]:
data['test result '].value_counts()

0.0    75
1.0    69
Name: test result , dtype: int64

In [21]:
data[data['test result ']==1]['treatment'].value_counts()

3     56
34    12
Name: treatment, dtype: int64

In [38]:
# Filter data where 'test result ' is 1 and 'treatment' is either '3' or '34' and count 'treatment result'
data[(data['test result ']==1) & ((data['treatment']==str(3)) | (data['treatment']==str(34)) )]['treatment result'].value_counts()

1.0    33
2.0    25
0.0    10
Name: treatment result, dtype: int64